"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True otherwise False");
console.log(car == 'subaru');
let country = 'Pakistan';
console.log("Is country == 'Pakistan'? I predict True otherwise False");
console.log(country == 'Pakistan');
let religion = 'Islam';
console.log("Is religion== 'Islam'? I predict true otherwise false");
console.log(religion == 'Islam');
let color = 'Magenta';
console.log("Is color == 'Magenta'? I predict true otherwise False");
console.log(color == 'Magenta');
let age = 59;
console.log("Is age == 59? I predict true otherwise false ");
console.log(age == 59);
let mobile = 'Iphone';
console.log("Is mobile == 'Iphone'? I predict true otherwise false ");
console.log(mobile == 'Xiaomi');
let flower = 'lily';
console.log("Is flower == 'lily' ? I predict true otherwis false");
console.log(flower == 'Rose');
let device = 'laptop';
console.log("Is device == 'laptop'? I predict true otherwise false ");
console.log(device == 'computer');
let animal = 'cat';
console.log("Is animal == 'cat'? I predict true otherwise false ");
console.log(animal == 'Lion');
let drink = 'Sprite';
console.log("Is drink == 'Sprite'? I predict true otherwise false");
console.log(drink == 'Fanta');
